// Liste des nationalités
export const nationalities = [
  "France",
  "Espagne",
  "Italie",
  "Allemagne",
  "Angleterre",
  "Portugal",
  "Belgique",
  "Suisse",
  "Pays-Bas",
  "Autriche",
  "Pologne",
  "République Tchèque",
  "Slovaquie",
  "Hongrie",
  "Grèce",
  "Turquie",
  "Roumanie",
  "Bulgarie",
  "Croatie",
  "Serbie",
  "Monténégro",
  "Bosnie-Herzégovine",
  "Macédoine",
  "Albanie",
  "Brésil",
  "Argentine",
  "Uruguay",
  "Chili",
  "Colombie",
  "Mexique",
  "États-Unis",
  "Canada",
  "Japon",
  "Corée du Sud",
  "Chine",
  "Australie",
  "Nouvelle-Zélande",
  "Afrique du Sud",
  "Égypte",
  "Maroc",
  "Algérie",
  "Tunisie",
  "Sénégal",
  "Côte d'Ivoire",
  "Nigeria",
  "Ghana",
];

export const shortNationalities: Record<string, string> = {
  France: "FRA",
  Espagne: "ESP",
  Italie: "ITA",
  Allemagne: "DEU",
  Angleterre: "GB-ENG",
  Portugal: "POR",
  Belgique: "BEL",
  Suisse: "SUI",
  "Pays-Bas": "NLD",
  Autriche: "AUT",
  Pologne: "POL",
  "République Tchèque": "CZE",
  Slovaquie: "SVK",
  Hongrie: "HUN",
  Grèce: "GRE",
  Turquie: "TUR",
  Roumanie: "ROU",
  Bulgarie: "BUL",
  Croatie: "CRO",
  Serbie: "SRB",
  Monténégro: "MNE",
  "Bosnie-Herzégovine": "BIH",
  Macédoine: "MKD",
  Albanie: "ALB",
  Brésil: "BRA",
  Argentine: "ARG",
  Uruguay: "URU",
  Chili: "CHI",
  Colombie: "COL",
  Mexique: "MEX",
  "États-Unis": "USA",
  Canada: "CAN",
  Japon: "JPN",
  "Corée du Sud": "KOR",
  Chine: "CHN",
  Australie: "AUS",
  "Nouvelle-Zélande": "NZL",
  "Afrique du Sud": "ZAF",
  Égypte: "EGY",
  Maroc: "MAR",
  Algérie: "DZA",
  Tunisie: "TUN",
  Sénégal: "SEN",
  "Côte d'Ivoire": "CIV",
  Nigeria: "NGA",
  Ghana: "GHA",
};
